### ISSUE TITLE
"403 Forbidden" error when loading page

### ISSUE THREAD

**Issue by MoritzBrueckner** [tong/armory_examples_browser#2]
https://disktree.net/app/armory_examples_browser/ currently shows a `403 FORBIDDEN` error message. Other members of the Armory discord also confirmed this, so it seems to be a general problem with the website and not with an individual user.

**Comment by tong** [comment]
Should be fixed. Thanks!

**Comment by MoritzBrueckner** [comment]
Works again, thanks a lot!
