### ISSUE TITLE
Example light_probes shouldn't exist

### ISSUE THREAD

**Issue by MoritzBrueckner** [tong/armory_examples_browser#3]
Hi,

first of all I had to open the issue here because https://github.com/armory3d/armory_examples_browser doesn't allow issues, I guess we should ask Lubos to enable that.

The examples browser contains an example https://armory3d.github.io/armory_examples_browser/#examples-light_probes that doesn't exist in the armory_examples repo, but I suspect it existed a while ago because I also had an empty folder for it in my local example repo. When running the example in the example browser, you see some artifacts and you can't really do much. Maybe it's caused by some old compiled build folders that are still around in the built example browser?

If it's not already the case, it would probably be the best to do a full and clean clone each time the examples browser is updated.

PS: Is it possible to add a link to the example browser repo somewhere in the example browser?

**Comment by rpaladin** [comment]
Once resolved, the wiki section relating to currently invalid light-probes will also need to be updated:
<https://github.com/armory3d/armory/wiki/global_illumination#light-probes>

**Comment by tong** [comment]
Originally there were two projects in light_probes, now split into:
- https://github.com/armory3d/armory_examples/tree/master/light_probes_cubemap
- https://github.com/armory3d/armory_examples/tree/master/light_probes_plane

The broken example was accidentally included from an unpublished project; removed. 

---

I've added links to repositories on the start site.
You can edit this here: https://github.com/armory3d/armory_examples_browser/blob/master/web/start.html

---

@luboslenco Can you please activate issues for the [armory organization fork](https://github.com/armory3d/armory_examples_browser)? This repo is deprecated.

**Comment by tong** [comment]
> Once resolved, the wiki section relating to currently invalid light-probes will also need to be updated: https://github.com/armory3d/armory/wiki/global_illumination#light-probes

Updated.

**Comment by luboslenco** [comment]
Done!

**Comment by MoritzBrueckner** [comment]
Thanks a lot! 🥳
